package verilog

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCorpusGolden runs the full pipeline over the real tests/*.sv corpus and
// asserts byte-equality with the Python oracle (goldens generated by
// gen_golden.sh). Some fixtures reference sub-modules in other fixtures, so the
// whole corpus is copied into a temp dir and resolution runs over it.
func TestCorpusGolden(t *testing.T) {
	testsDir := filepath.Join("..", "..", "..", "tests")
	entries, err := os.ReadDir(testsDir)
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".sv") {
			fixtures = append(fixtures, e.Name())
		}
	}
	if len(fixtures) == 0 {
		t.Fatal("no corpus fixtures found")
	}

	corpus := t.TempDir()
	for _, name := range fixtures {
		data, err := os.ReadFile(filepath.Join(testsDir, name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(corpus, name), data, 0644); err != nil {
			t.Fatal(err)
		}
	}

	for _, name := range fixtures {
		base := strings.TrimSuffix(name, ".sv")
		want, err := os.ReadFile(filepath.Join("..", "..", "testdata", "golden", "tests_"+base+".golden"))
		if err != nil {
			t.Fatalf("%s: missing golden (run go/testdata/gen_golden.sh): %v", name, err)
		}
		content, err := os.ReadFile(filepath.Join(corpus, name))
		if err != nil {
			t.Fatal(err)
		}
		proj := NewProject()
		needed := map[string]bool{}
		for _, inst := range GetInstantiations(string(content)) {
			needed[inst.ModuleName] = true
		}
		proj.Resolve([]string{corpus}, needed)
		got := ExpandAll(string(content), name, proj)
		if got != string(want) {
			t.Errorf("corpus mismatch: %s\n--- got ---\n%q\n--- want ---\n%q", name, got, string(want))
		}
	}
}
